sfdx-live-agent-util/main/default/objects/LiveAgent_Env__mdt/LiveAgent_Env__mdt.object-meta.xml
<CustomObject>
    <description>Live Agent config settings</description>
    <label>LiveAgent Env</label>
    <pluralLabel>LiveAgent Envs</pluralLabel>
</CustomObject>

sfdx-live-agent-util/main/default/objects/LiveAgent_Env__mdt/fields/baseLiveAgentContentURL__c.field-meta.xml
<CustomField>
    <fullName>baseLiveAgentContentURL__c</fullName>
    <label>baseLiveAgentContentURL</label>
    <type>Url</type>
</CustomField>

sfdx-live-agent-util/main/default/objects/LiveAgent_Env__mdt/fields/baseLiveAgentURL__c.field-meta.xml
<CustomField>
    <fullName>baseLiveAgentURL__c</fullName>
    <label>baseLiveAgentURL</label>
    <type>Url</type>
</CustomField>

sfdx-live-agent-util/main/default/objects/LiveAgent_Env__mdt/fields/brandURL__c.field-meta.xml
<CustomField>
    <fullName>brandURL__c</fullName>
    <label>brandURL</label>
    <type>Url</type>
</CustomField>

sfdx-live-agent-util/main/default/objects/LiveAgent_Env__mdt/fields/buttonId__c.field-meta.xml
<CustomField>
    <fullName>buttonId__c</fullName>
    <label>buttonId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfdx-live-agent-util/main/default/objects/LiveAgent_Env__mdt/fields/deploymentId__c.field-meta.xml
<CustomField>
    <fullName>deploymentId__c</fullName>
    <label>deploymentId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfdx-live-agent-util/main/default/objects/LiveAgent_Env__mdt/fields/eswLiveAgentDevName__c.field-meta.xml
<CustomField>
    <fullName>eswLiveAgentDevName__c</fullName>
    <label>eswLiveAgentDevName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

sfdx-live-agent-util/main/default/objects/LiveAgent_Env__mdt/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

sfdx-live-agent-util/main/default/classes/LiveAgentUtilSvcTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * LiveAgentUtilSvc.
 *
 *  
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * author: A.I.
 */
@isTest
private class LiveAgentUtilSvcTest {
    static testMethod void getLiveAgentEnvTest(){
	Organization org = LiveAgentUtilSvc.getOrgInfo();
        // === Start Test ===
        Test.startTest();        
        List<LiveAgentUtilSvc.LiveAgentEnv> lst = LiveAgentUtilSvc.getLiveAgentEnv();
        Test.StopTest();
	    
	List<LiveAgent_Env__mdt> envList = [SELECT Id, DeveloperName, Version__c, brandURL__c,
                                                 baseLiveAgentURL__c, baseLiveAgentContentURL__c, 
                                                 deploymentId__c, buttonId__c, eswLiveAgentDevName__c 
                                                 FROM LiveAgent_Env__mdt ];        
        System.assertEquals(lst.size(),envList.size());
        LiveAgentUtilSvc.LiveAgentEnv env = lst[0];
        System.assertEquals(env.orgId, org.Id);
    }

    static testMethod void queryDeploymentTest(){
	Organization org = LiveAgentUtilSvc.getOrgInfo();
        // === Start Test ===
        Test.startTest();        
        List<LiveAgentUtilSvc.LiveAgentEnv> lst = LiveAgentUtilSvc.queryDeployment('Test_Certificate');
        Test.StopTest();
	    
        System.assertEquals(lst.size(),1);
        LiveAgentUtilSvc.LiveAgentEnv env = lst[0];
        System.assertEquals(env.orgId, org.Id);
    }
}